### ISSUE TITLE
destroyPlayer() does not remove player in cache

### ISSUE THREAD

**Issue by zvyap** [lavalink-devs/lavalink-client#17]
After looking at the source code of the lavalink-client, the LavalinkPlayer should be remove from cache after calling destoryPlayer() method

But it don't.

![image](https://github.com/lavalink-devs/lavalink-client/assets/52874570/ce5440de-4a3b-4ca8-874a-0a499df7fa93)
![image](https://github.com/lavalink-devs/lavalink-client/assets/52874570/72ff0162-0175-45ed-924d-0c23b843f393)

Source code
![image](https://github.com/lavalink-devs/lavalink-client/assets/52874570/4cd5909c-7201-4d9b-86bc-11400964573f)

**Comment by duncte123** [comment]
Please don't use the weirdly named methods. You're supposed to use getPlayer() as that will check the cache first

**Comment by zvyap** [comment]
> Please don't use the weirdly named methods. You're supposed to use getPlayer() as that will check the cache first

I don't want it to create a new player as getPlayer() will create a new player if the cache is not exist
Why I want to create a new player if I already want to destory the player if exist.....

**Comment by zvyap** [comment]
> > > Please don't use the weirdly named methods. You're supposed to use getPlayer() as that will check the cache first
> > 
> > 
> > I don't want it to create a new player as getPlayer() will create a new player if the cache is not exist Why I want to create a new player if I already want to destory the player if exist.....
> 
> Then there seems to be a flaw in your code. If you just want to destroy the player, there is no need to check if it exists. Also, if you are using the JDA or D4J integration, the player will be automatically destroyed when your bot leaves the voice channel

Im not using either JDA or D4J, Im making a global service handling all of my track stuff (Web controller/Bot/Other)

Im doing the check because I want to know if the player is exist previously, if Im using `node.destroyPlayer()`, I will not know that.
It also send a destroy rest action which it add extra latency to my service.

**Comment by duncte123** [comment]
You can always check the connected status on the link. If it is connected, you have a player. Also, if you call `subscribe()` instead of `block()` te request will be done asynchronously, meaning that there is no added latency

**Comment by duncte123** [comment]
Either way, this was fixed in version 2.2.0
