### ISSUE TITLE
PlayerUpdateBuilder trackUpdate got overwrites once other method got called

### ISSUE THREAD

**Issue by zvyap** [lavalink-devs/lavalink-client#19]
The setEncodedTrack action got override by other action call that modify track data.
![image](https://github.com/lavalink-devs/lavalink-client/assets/52874570/f155992d-6f41-4159-8f3f-0bbcc7449870)

Some method update override correctly (stopTrack, setTrack), but not those actions that do not conflict with each other (setEncodedTrack, setIdentifier).

Source code will explain more clearly
![image](https://github.com/lavalink-devs/lavalink-client/assets/52874570/9870c747-1bb0-40fe-bebc-46d571d53325)

**Comment by duncte123** [comment]
You cannot set the identifier and the encoded track at the same time. The documentation specifies that those setters override all fields.
I'll create a builder so people can set only the fields they need.
