### ISSUE TITLE
Failures in Detection and Transfer

### ISSUE THREAD

**Issue by WeeeeeeeeeeS** [lavalink-devs/lavalink-client#29]
1) Failing to connect to the node doesn't mark it as unavailable 
2) If a used node was removed. the client won't transfer it to an available one 
3) Nonstop timeouts don't mark the node as a failing one (after restarting the node it spammed session not found) 

^If you kill the host, it will throw nonstop timeouts

**Comment by duncte123** [comment]
> If a used node was removed. the client won't transfer it to an available one
What does "it" refer to here? A node cannot be transferred to another node.

**Comment by WeeeeeeeeeeS** [comment]
I mean that the client won't transfer the players to another node when a node shuts down/becomes unavailable/removed

**Comment by duncte123** [comment]
What version of the client are you using?

**Comment by WeeeeeeeeeeS** [comment]
lavalinkClientVersion=3.0.0
